apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: regapp
spec:
  selector:
    app: regapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # Replace 30080 with your desired NodePort value
  type: NodePort

